### ISSUE TITLE
Sources

### ISSUE THREAD

**Issue by benfoxall** [mubaidr/contours.ts#7]
Hey @mubaidr 👋 .

The [initial commit](https://github.com/mubaidr/contours.ts/commit/4f2d02a5f2d763efc4f28e8a06e15f88fa2150fb) of this project contains code from [benfoxall/contours](https://github.com/benfoxall/contours).

To be clear; I'm extremely happy about this, I'm so glad the code I wrote was useful to you.  It looks like you've made a substantial improvement to it and the docs seem a lot cleaner too.  Also, thanks a lot for feeding back a change to mine.

Though, I'd also really appreciate if you'd mention my contribution, perhaps you could:

* Add a `Copyright (c) 2017 Ben Foxall` row to your `LICENSE` file? (via [this SO](https://opensource.stackexchange.com/questions/2391/how-should-i-assert-copyright-when-im-forking-an-mit-project))
* Link to [my project](https://github.com/benfoxall/contours) and this [algorithm source](http://www.imageprocessingplace.com/downloads_V3/root_downloads/tutorials/contour_tracing_Abeer_George_Ghuneim/moore.html) in your `README`

If you were to do this, I'd be more than happy to point people at your project as a more modern & maintained version.

Ben

**Comment by mubaidr** [comment]
Hi!

Thanks for your valuable feedback!

I started from your code as base, even had a repo clone to continue improve on it. But as soon I started working I noticed it will be better to re-write internals. You can confirm this by checking code, only `cache` part is similar. 

I think, since all code parts have been replaced (since this commit: https://github.com/mubaidr/contours.ts/commit/61e189ea132961a88cd106e6026c6c8eef41cd11), it is fair to keep the current license. But nonetheless, this code base is inspired by your project ([benfoxall/contours](github.com/benfoxall/contours)) and this one here: ([Dkendal/Moore-Neighbor_Contour_Tracer](github.com/Dkendal/Moore-Neighbor_Contour_Tracer)). 
I be will updating readme to reflect that. 

I have added `Ramer Douglas Peucker Algorithm` to this repo too and plan to update readme about all the functions and algorithms used and links to the sources of algorithms.

**Comment by benfoxall** [comment]
Thanks for the quick reply!

Yeah, that makes sense about the licence. I'm always a bit unsure about how to handle bringing in other code & licences, but I think you're correct that it's fair to keep your licence since you've rewritten everything.  (especially since they're both MIT).

Oh, I look forward to finding out how the Ramer Douglas Peucker Algorithm compares!  Have you got plans for a demo page? There's one on my [`/docs`](https://github.com/benfoxall/contours/tree/master/docs) ([live version](https://benjaminbenben.com/contours/)), that you'd be welcome to (with attribution of course!!)

It sounds like this is going to be more useful than my project was, so let me know if you'd like to take over the [`contours`](https://www.npmjs.com/package/contours) npm package.  I'm not entirely sure what's involved in doing that, but I'd be happy to hand it over if you'd like it.

**Comment by mubaidr** [comment]
I have updated readme to add `Acknowledgements` section. 👍🏼 

`Ramer Douglas Peucker Algorithm` is used to simplify polygons/contours to minimum set of points. My plan is to reduce obtained contours to simple shapes (if possible) i.e. `Rectangle`, `Circle` etc Its in progress though. Basic tests run fine, but shape mapping need effort. 

Definity, a live demo page will be an awesome addition. I am thinking of adding some using `codesandbox.io`. What do you think? 

Currently I have pushed npm package as `contours.ts`, but we can do `contours`. 

@all-contributors please add @benfoxall for code

**Comment by mubaidr** [comment]
@all-contributors please add @benfoxall for code

**Comment by mubaidr** [comment]
https://github.com/mubaidr/contours.ts/commit/4d05cf60df5bb35e50fe75eda699b394d61badc6
